- name: print app version
  ansible.builtin.debug:
    msg: "App version is:{{app_version}}"

- name: Install NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Setup Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: Load Schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mongo-schema

- name: Start application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup
